name: Android CD with Fastlane

on:
  push:
    branches: [ master ]

jobs:
  baselineprofile:
    name: Generate baseline profile
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip cd]')"
    timeout-minutes: 120

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Copy baseline profile gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/bp-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Decrypt secrets
        run: ./.secrets/scripts/decrypt.sh "$secret_key"
        env:
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install GMD image for baseline profile generation
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager "system-images;android-33;aosp_atd;x86_64"

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Clean Managed Devices
        run: ./gradlew cleanManagedDevices --unused-only

      - name: Generate Baseline Profile
        run: ./gradlew generateBaselineProfile
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
          -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
          -Pandroid.experimental.androidTest.numManagedDeviceShards=1
          -Pandroid.experimental.testOptions.managedDevices.maxConcurrentDevices=1

      - name: Commit Baseline Profiles
        run: |
          git config --global user.name 'Baseline Profiles - GitHub Actions'
          git config --global user.email 'github@actions'
          git add app/src/release/generated/baselineProfiles/baseline-prof.txt
          git commit -m "chore: Generate baseline profiles"
          git push

  deploy:
    name: Deploy to Google Play Store
    runs-on: ubuntu-latest
    needs:
      - baselineprofile
    if: "!contains(github.event.head_commit.message, '[skip cd]')"

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Make scripts executable
        run: chmod -R +x ./.secrets/scripts

      - name: Decrypt secrets
        run: ./.secrets/scripts/decrypt.sh "$secret_key"
        env:
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Deploy to Google Play Store
        run: bundle exec fastlane deploy

  tag:
    name: Push git tag
    needs: deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip cd]')"

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
