name: Android CI with Gradle

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make scripts executable
        run: chmod -R +x ./.secrets/scripts

      - name: Decrypt secrets
        run: ./.secrets/scripts/decrypt.sh "$secret_key"
        env:
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Disabled spotless temporarily, as it was causing too many lint errors by not putting modifiers in Composable.
      # - name: Check spotless
      # run: ./gradlew spotlessCheck --stacktrace

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
